routes/web.php
<?php

Route::group(['namespace' => 'Sentinel'], function () {
    Route::middleware('guest')->group(function () {
        Route::get('login', 'LoginController@getLogin');
        Route::get('signup', 'RegisterController@getRegister');

        Route::get('signup/borrower/{profile_type?}', 'RegisterController@getRegisterBorrower');
        Route::get('signup/lender', 'RegisterController@getRegisterLender');

        Route::post('signup/borrower', 'RegisterController@postRegisterBorrower');
        Route::post('signup/lender', 'RegisterController@postRegisterLender');

        Route::get('activate/{user}/{activation_code}', 'ActivationController@getActivate');

        Route::get('forgot/password', 'ForgotPasswordController@getForgetPassword');
        Route::post('forgot/password', 'ForgotPasswordController@postForgetPassword');
        Route::get('forgot/confrm', 'ForgotPasswordController@getForgetConfirm');

        Route::get('reset/password/{user}/{reset_code}', 'ResetPasswordController@getResetPassword');
        Route::post('reset/password', 'ResetPasswordController@postResetPassword');
        Route::get('reset/error', 'ResetPasswordController@getResetError');

        Route::get('get-loans', 'RegisterController@getRegisterBorrower');
        Route::get('aspire-borrowers', 'RegisterController@getRegisterBorrower');
    });

    Route::post('login', 'LoginController@postLogin');
    Route::get('logout', 'LoginController@getLogout');
});

Route::group(['namespace' => 'Admin'], function () {
    Route::get('institutions/check_domain_taken', 'InstitutionController@isNewDomainValid');
    Route::get('users/check_email_exists', 'UserController@isNewEmailValid');

    Route::get('states/check_enabled', 'StateController@checkEnabled');
    Route::get('states/check_city_enabled', 'StateController@checkCityEnabled');

    Route::get('states/check_zipcode_enabled', 'StateController@checkZipCodeEnabled');
    Route::get('states/check_valid_zip_code', 'StateController@checkValidZipCode');
});
Route::group(['prefix' => 'dropdowns'], function () {
    Route::get('zip_codes', 'DropdownsControllers@zipCodes'); //dy mfrod tb2a zip_codes
    Route::get('zip_codes_for_city', 'DropdownsControllers@zipCodesForCity');

    Route::get('cities', 'DropdownsControllers@cities'); //dy mfrood tb2a cities

    Route::get('states', 'DropdownsControllers@states');

    Route::get('counties', 'DropdownsControllers@counties');
});

Route::middleware(['auth', 'web', 'permissions'])->group(function () {

    Route::get('/', 'HomeController@getIndex')->name('home');

    Route::middleware('subscribed')->group(function () {
        Route::get('braintree/token', 'BraintreeTokenController@token');
        Route::resource('subscribe', 'SubscriptionsController');
    });

    Route::get('user/invoice/{invoice}', 'SubscriptionsController@invoice');

    Route::post('upload_files', 'AttachmentController@uploadFiles')->name('upload_files');
    Route::post('upload_file', 'AttachmentController@uploadFile')->name('upload_file');
    Route::resource('attachment', 'AttachmentController');

    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'admin'], function () {

        Route::get('/', 'DashboardController@getIndex')->name('admin.home');

        Route::get('dashboard', 'DashboardController@getIndex')->name('dashboard');
        Route::get('dashboard_2', 'DashboardController@getIndex2')->name('dashboard2');
        Route::get('dashboard_3', 'DashboardController@getIndex3')->name('dashboard3');

        Route::group(['prefix' => 'institutions'], function () {

            Route::put('{institution}/change_status', 'InstitutionController@changeStatus')->name('institutions.change_status');
            Route::get('institution_loan_handling_chart', 'InstitutionController@institutionLoanHandlingChart'); //Returns JSON
        });

        Route::resource('institutions', 'InstitutionController');

        Route::put('institution_types/{institution_type}/change_status', 'InstitutionTypeController@changeStatus')->name('institution_types.change_status');
        Route::resource('institution_types', 'InstitutionTypeController');

        Route::put('institution_sizes/{institution_size}/change_status', 'InstitutionSizeController@changeStatus')->name('institution_sizes.change_status');
        Route::resource('institution_sizes', 'InstitutionSizeController');

        Route::group(['prefix' => 'users'], function () {
            Route::put('{user}/change_status', 'UserController@changeStatus')->name('users.change_status');
            Route::get('{user}/tracks/{user_track}', 'UserController@showTrack')->name('users.track'); //to be checked
        });
        Route::resource('users', 'UserController');

        Route::get('lenders_per_state', 'UserController@lendersPerState');

        Route::get('number_of_lenders_per_institution', 'UserController@numberOfLendersPerInstitution');

        Route::get('loans_feedback_statistics', 'FeedbackController@loansFeedbackStatistics');

        Route::resource('roles', 'RoleController');

        Route::put('real_estate_types/{real_estate_type}/change_status', 'RealEstateTypeController@changeStatus')->name('real_estate_types.change_status');
        Route::resource('real_estate_types', 'RealEstateTypeController');

        Route::put('property_types/{property_type}/change_status', 'PropertyTypeController@changeStatus')->name('property_types.change_status');
        Route::resource('property_types', 'PropertyTypeController');

        Route::put('purpose_types/{purpose_type}/change_status', 'PurposeTypeController@changeStatus')->name('purpose_types.change_status');
        Route::resource('purpose_types', 'PurposeTypeController');

        Route::put('lease_types/{lease_type}/change_status', 'LeaseTypeController@changeStatus')->name('lease_types.change_status');
        Route::resource('lease_types', 'LeaseTypeController');

        Route::resource('settings', 'SettingController');

        Route::group(['prefix' => 'states/{state}'], function () {

            Route::put('change_status', 'StateController@changeStatus')->name('states.change_status'); //done
            Route::get('counties', 'StateController@counties')->name('counties.index');

            Route::group(['prefix' => 'counties'], function () {
                Route::post('select_all' , 'StateController@selectAllCounties');
                Route::post('unselect_all' , 'StateController@unselectAllCounties');

                Route::put('{county}/change_status', 'StateController@changeCountyStatus')->name('counties.change_status');
                Route::get('{county}/cities', 'StateController@cities')->name('cities.index');

                Route::post('{county}/cities/select_all' , 'StateController@selectAllCities') ;
                Route::post('{county}/cities/unselect_all' , 'StateController@unselectAllCities') ;

                Route::group(['prefix' => '{county}/cities/{city}'], function () {
                    Route::post('zip_codes/select_all' , 'StateController@selectAllZipCodes') ;
                    Route::post('zip_codes/unselect_all' , 'StateController@unselectAllZipCodes') ;

                    Route::put('change_status', 'StateController@changeCityStatus')->name('cities.change_status');
                    Route::get('zip_codes', 'StateController@zip_codes')->name('zip_codes.index');

                    Route::group(['prefix' => 'zip_codes/{zip_code}'], function () {
                        Route::put('change_status', 'StateController@changeZipCodeStatus')->name('zip_codes.change_status');
                    });
                });
            });

        });
        Route::post('states/select_all', 'StateController@selectAllStates');
        Route::post('states/unselect_all', 'StateController@unselectAllStates');

        Route::resource('states', 'StateController');

        Route::get('loans/bids/{bid}/show', 'LoanController@showBid');
        Route::get('loans/bids', 'LoanController@bids');

        Route::resource('loans', 'LoanController');

        Route::get('loans_count', 'LoanController@loansCount'); // Returns JSON
        Route::get('loans_status_statistics', 'LoanController@loansStatusStatistics'); //Returns JSON
        Route::get('total_number_of_loans', 'LoanController@totalNumberOfLoans'); // Returns JSON


    });

    Route::group(['namespace' => 'Agent'], function () {

        Route::get('profile', 'UserController@show')->name('profile');
        Route::get('account', 'UserController@edit')->name('account');

        Route::get('preferences', 'PreferenceController@index')->name('preferences.index');

        Route::group(['prefix' => 'users'], function () {
            Route::put('{user}/account_settings', 'UserController@update')->name('user.account_settings');
            Route::put('{user}/change_password', 'UserController@changePassword')->name('user.change_password');
            Route::put('{user}/change_picture', 'UserController@changePicture')->name('user.change_picture');
            Route::put('{user}/notification_settings', 'UserController@updatePreferences')->name('user.notification_settings');
            Route::put('{user}/preferences', 'UserController@updatePreferences')->name('user.preferences');
        });

        Route::put('notifications/{notification}/mark_read', 'NotificationController@markAsRead')->name('notification.mark_read');
        Route::put('notifications/mark_all_read', 'NotificationController@markAllRead')->name('notifications.mark_all_read');

        Route::resource('notifications', 'NotificationController');

        Route::post('conversations/{conversation}/replies', 'ConversationController@addReply')->name('conversation.add_reply');
        Route::put('conversations/mark_all_read', 'ConversationController@markAllRead')->name('conversations.mark_all_read');

app/Models/User.php
<?php

namespace App\Models;

use App\Enums\ActivationStates;
use Carbon\Carbon;
use Cartalyst\Sentinel\Users\EloquentUser;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Cashier\Billable;

class User extends EloquentUser
{
    use SoftDeletes, Billable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'status'
    ];

    protected $dates = ['deleted_at', 'trial_ends_at'];


    public function lenderProfile()
    {
        return $this->hasOne('App\Models\LenderProfile', 'user_id');
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getUserRoleNameAttribute()
    {
        $roles_name = '';
        if ($this->roles) {
            foreach ($this->roles as $role) {
                $roles_name .= $role->name;
            }
        }
        return $roles_name;
    }

    public function getLenderBidsCountAttribute()
    {
        return count($this->lender_bids);
    }

    public function getBorrowerLoansCountAttribute()
    {
        return count($this->borrower_loans);
    }

    public function getRoleAttribute()
    {
        return $this->roles[0];
    }

    public function borrowerProfiles()
    {
        return $this->hasMany('App\Models\BorrowerProfile', 'user_id', 'id');
    }

    public function tracks()
    {
        return $this->hasMany('App\Models\UserTrack', 'user_id', 'id');
    }

    public function preferences()
    {
        return $this->hasMany('App\Models\Preference', 'user_id', 'id');
    }

    public function borrower_loans()
    {
        return $this->hasMany('App\Models\Loan', 'borrower_id', 'id');
    }

    public function archived_loans()
    {
        return $this->belongsToMany('App\Models\Loan', 'loan_archive', 'user_id', 'loan_id');
    }

    public function lender_bids(){
        return $this->hasMany('App\Models\Bid', 'lender_id', 'id');
    }

    public function scopeActive($query)
    {
        return $query->where('status', ActivationStates::ACTIVE);
    }
    public function scopeFirstReminder($query)
    {
        return $query->where('free_lifetime', 0)
            ->where('first_reminder_email_sent', 0)
            ->where('second_reminder_email_sent', 0)
            ->where('third_reminder_email_sent', 0);
    }

    public function scopeSecondReminder($query)
    {
        return $query->where('free_lifetime', 0)
            ->where('first_reminder_email_sent', 1)
            ->where('second_reminder_email_sent', 0)
            ->where('third_reminder_email_sent', 0);
    }

    public function scopeThirdReminder($query)
    {
        return $query->where('free_lifetime', 0)
            ->where('first_reminder_email_sent', 1)
            ->where('second_reminder_email_sent', 1)
            ->where('third_reminder_email_sent', 0);
    }

    public function scopeTrialEndsWithinDays($query, $days)
    {
        return $query->where('trial_ends_at', '<=', Carbon::now()->addDays($days));
    }

}

app/Http/Controllers/Agent/Borrower/HomeController.php
<?php

namespace App\Http\Controllers\Agent\Borrower;


class HomeController
{
    public function index()
    {
        return redirect()->route('borrower.get-loans');
    }
}

app/Http/Controllers/Agent/Lender/ProfileController.php
<?php

namespace App\Http\Controllers\Agent\Lender;

use App\Models\LenderProfile;
use App\Models\User;
use App\Services\LenderProfileService;
use App\Traits\ControllersTrait;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Sentinel;
use Storage;

class ProfileController extends Controller
{
    use ControllersTrait;

    protected $lenderProfileService;

    public function __construct(LenderProfileService $lenderProfileService)
    {
        $this->setMessagesKey('lender_profiles');
        $this->lenderProfileService = $lenderProfileService;
    }

    public function update(Request $request, LenderProfile $profile)
    {
        $response = $this->lenderProfileService->update($profile, $request->except(['_method', '_token', 'save_continue_tab']));
        return $this->handleReponse($request, $response);
    }

}

app/Http/Controllers/Frontend/Lender/ProfileController.php
<?php

namespace App\Http\Controllers\Frontend\Lender;

use App\Models\LenderProfile;
use App\Models\User;
use App\Traits\ControllersTrait;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Sentinel;
use Storage;
use App\Services\UserService;

class ProfileController extends Controller
{
    use ControllersTrait;

    protected $userService;

    public function __construct(UserService $userService)
    {
        $this->setMessagesKey('lender_profiles');
        $this->userService = $userService;
    }

    public function update(Request $request, User $lender, LenderProfile $profile)
    {
        $response = $this->userService->updateLenderProfile($profile, $request->except(['_method', '_token', 'save_continue_tab']));
        return $this->handleReponse($request, $response);
    }

}

resources/views/v1/cp/agent/borrower/profiles/create.blade.php
@extends('v1.layout.agent')

@section('page-title')
    {{ $user->full_name ." ". trans('messages.users.profile')}}
@endsection

@section('page-css-pugins')
    <link href="{{asset('assets/pages/css/profile-2.min.css')}}" rel="stylesheet" type="text/css"/>

    <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet"
          type="text/css"/>

@endsection

@section('page-breadcrumb')
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">{{trans('messages.home')}}</a>
            <span class="separator">/</span>
        </li>
        <li>
            <span class="active">{{trans('messages.profiles.add_profile')}}</span>
        </li>
    </ul>
@endsection

@php
    if($profile_type == BorrowerProfileTypes::REAL_ESTATE)
    {
    $form_id = 'borrower_realEstate_profile';
    }
    else
    {
    $form_id = 'borrower_business_profile';
    }

@endphp

@section('content')
    <div class="row">
        <div class="col-md-12">
            <form id="{{$form_id}}" class="form-horizontal form-row-seperated"
                  action="{{url('borrower/profiles')}}" method="POST">
                <input type="hidden" name="_token" value="<?= csrf_token() ?>">
                <input type="hidden" name="save_continue" id="save_continue" value="no">
                <input type="hidden" name="profile_type" id="profile_type" value="{{$profile_type}}">

                <div class="portlet">
                    <div class="portlet-title">
                        <div class="caption">
                            </i>{{trans('messages.operations.add')}}
                            {{$profile_type == BorrowerProfileTypes::REAL_ESTATE ? trans('messages.sign_up_borrower.real_Estate') : trans('messages.sign_up_borrower.business')}}
                            {{trans('messages.users.profile')}}
                        </div>
                        <div class="actions btn-set">
                            <button type="button" class="btn btn-secondary-outline btn_action_back">
                                <i class="fa fa-angle-left"></i> {{trans('messages.operations.back')}}
                            </button>
                            <button class="btn btn-secondary-outline btn_action_reload">
                                <i class="fa fa-reply"></i> {{trans('messages.operations.reset')}}
                            </button>
                            <button type="button" class="btn btn-success btn_action_save">
                                <i class="fa fa-check"></i> {{trans('messages.operations.save')}}
                            </button>
                        </div>
                    </div>
                    {{--col-md-10 col-md-offset-1--}}
                    <div class="portlet-body">
                        <div class="tabbable-bordered">
                            <div class="tab-content">
                                <div class="form-body">
                                    @if($profile_type == BorrowerProfileTypes::REAL_ESTATE)
                                        @include('v1.cp.components.user.realestate_profile',['profile'=>null])
                                    @else
                                        @include('v1.cp.components.user.business_profile',['profile'=>null])
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
@endsection

@section('page-js-pugins')
    <script src="{{asset('assets/global/plugins/jquery-repeater/jquery.repeater.js')}}" type="text/javascript"></script>

    <script src="{{asset('assets/global/plugins/jquery-validation/js/jquery.validate.min.js')}}"
            type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/jquery-validation/js/additional-methods.min.js')}}"
            type="text/javascript"></script>
    <script src="{{asset('assets/loan-app/scripts/custom_validation_methods.js')}}"></script>

    <script src="{{asset('assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js')}}"
            type="text/javascript"></script>

    <script src="{{asset('assets/global/plugins/select2/js/select2.full.min.js')}}" type="text/javascript"></script>

    <script src="{{asset('assets/global/plugins/masks/jquery.maskMoney.min.js')}}"
            type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.13.4/jquery.mask.min.js"></script>

@endsection

@section('page-scripts')
    <script src="{{asset('assets/loan-app/scripts/datatable-simple.js')}}"></script>
    <script src="{{asset('assets/loan-app/scripts/general/address.js')}}"></script>
    <script src="{{asset('assets/loan-app/scripts/users/borrower_profile.js')}}"></script>
@endsection

resources/views/v1/cp/agent/borrower/profiles/create_type.blade.php
@extends('v1.layout.agent')

@section('page-title')
    {{ $user->full_name ." ". trans('messages.profiles.add_profile')}}
@endsection

@section('page-css-pugins')
    <link href="{{asset('assets/pages/css/profile-2.min.css')}}" rel="stylesheet" type="text/css"/>

    <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet"
          type="text/css"/>
    <link href="{{asset('assets/pages/css/about.min.css')}}" rel="stylesheet" type="text/css"/>

@endsection

@section('page-breadcrumb')
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">{{trans('messages.home')}}</a>
            <span class="separator">/</span>
        </li>
        <li>
            <span class="active">{{trans('messages.profiles.add_profile')}}</span>
        </li>
    </ul>
@endsection

@section('content')
    <div class="margin-top-40">
    <div class="col-md-8 col-md-offset-2">
        <div class="text-center">
            <h1 class="m-xs-top-bottom tell_us"><?= trans('messages.profiles.select_profile_type')?></h1>
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2" style="margin-top: 30px">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="portlet">
                    <div class="card-icon card-icon-signup">
                        <img class="img-icon-signup" src="{{asset('assets/loan-app/img/bussniss-Loan.png')}}">
                    </div>
                    <div class="card-title">
                        <span> {{trans('messages.sign_up_borrower.business')}} </span>
                    </div>
                    <div class="card-desc">
                        <a class="btn btn-default btn-circle uppercase"
                           href="{{url('borrower/profiles/create?profile_type=business')}}"><?= trans('messages.sign_up_borrower.get_started')?></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="portlet">
                    <div class="card-icon card-icon-signup">
                        <img class="img-icon-signup" src="{{asset('assets/loan-app/img/realstate-Loan.png')}}">
                    </div>
                    <div class="card-title">
                        <span> {{trans('messages.sign_up_borrower.real_Estate')}} </span>
                    </div>
                    <div class="card-desc">
                        <a class="btn btn-default btn-circle uppercase"
                           href="{{url('borrower/profiles/create?profile_type=real_estate')}}"><?= trans('messages.sign_up_borrower.get_started')?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

@section('page-js-pugins')
    <script src="{{asset('assets/global/plugins/jquery-repeater/jquery.repeater.js')}}" type="text/javascript"></script>

    <script src="{{asset('assets/global/plugins/jquery-validation/js/jquery.validate.min.js')}}"
            type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/jquery-validation/js/additional-methods.min.js')}}"
            type="text/javascript"></script>
    <script src="{{asset('assets/loan-app/scripts/custom_validation_methods.js')}}"></script>

    <script src="{{asset('assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js')}}"
            type="text/javascript"></script>

    <script src="{{asset('assets/global/plugins/select2/js/select2.full.min.js')}}" type="text/javascript"></script>

@endsection

@section('page-scripts')
    <script src="{{asset('assets/loan-app/scripts/datatable-simple.js')}}"></script>
    <script src="{{asset('assets/loan-app/scripts/users/borrower_profile.js')}}"></script>
@endsection

resources/views/v1/cp/agent/borrower/profiles/index.blade.php
@extends('v1.layout.agent')

@section('page-title')
    {{ $user->full_name ." ". trans('messages.users.profile')}}
@endsection

@section('page-css-pugins')
    <link href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"
          rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/pages/css/profile-2.min.css')}}" rel="stylesheet" type="text/css"/>
@endsection

@section('page-head')
    <div class="page-head">
        <div class="page-title">
            <h1>{{ $user->full_name ." ". trans('messages.users.profiles')}}</h1>
        </div>
        <div class="page-toolbar">
            <a class="btn btn-success " href="{{url('borrower/profiles/create')}}">
                <i class="fa fa-plus"></i>
                <span class="hidden-xs"> {{trans('messages.header_frontend.add_profile')}} </span>
            </a>

        </div>
    </div>
@endsection

@section('page-breadcrumb')
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">{{trans('messages.home')}}</a>
            <span class="separator">/</span>
        </li>
        <li>
            <span class="active">{{ $user->full_name ." ". trans('messages.users.profiles')}}</span>
        </li>
    </ul>
@endsection

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-advance table-hover"
                           id="data_table_no_actions">
                        <thead>
                        <tr>
                            <th></th>
                            <th>{{trans('messages.profiles.profile_type')}}</th>
                            <th>{{trans('messages.profiles.title')}}</th>
                            <th>{{trans('messages.profiles.is_enabled')}}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($profiles)
                            @foreach($profiles as $record)
                                <tr>
                                    <td>
                                        @if($record->id == session('borrower_profile_id'))
                                            <span class="label label-sm label-success"> {{trans('messages.profiles.active')}} </span>
                                        @endif
                                    </td>
                                    <td>{{$record->profile_type}}</td>
                                    <td>{{$record->profile_title or ''}}</td>
                                    <td>
                                        <form id="changeStateForm{{$record->id}}" class="form-horizontal"
                                              action="{{url('borrower/profiles/' . $record->id . '/change_status')}}"
                                              method="POST">
                                            <input type="hidden" name="_method" value="PUT">
                                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                                            <input type="hidden" name="is_enabled" value="{{$record->is_enabled}}">

                                            <input type="checkbox" class="make-switch" data-size="small"
                                                   data-bind="{{$record->id}}"
                                                   {{$record->is_enabled ? "checked" : ""}} data-on-color='success'
                                                   data-on-text="<i class='fa fa-check'></i>"
                                                   data-off-text="<i class='fa fa-times'></i>">
                                        </form>
                                    </td>
                                    <td>
                                        <a class="btn btn-sm grey-salsa btn-outline"
                                           href="{{url('borrower/profiles/'.$record->id)}}">
                                            <i class="fa fa-eye"></i>
                                            <span class="hidden-xs"> {{trans('messages.operations.view')}} </span>
                                        </a>
                                        <a class="btn btn-sm grey-salsa btn-outline"
                                           href="{{url('borrower/profiles/'.$record->id.'/edit')}}">
                                            <i class="fa fa-edit"></i>
                                            <span class="hidden-xs"> {{trans('messages.operations.edit')}} </span>
                                        </a>
                                        <a class="btn btn-sm grey-salsa btn-outline" data-toggle="modal"
                                           href="#deleteModal{{$record->id}}">
                                            <i class="fa fa-close"></i>
                                            <span class="hidden-xs"> {{trans('messages.operations.delete')}} </span>
                                        </a>
                                        @include('v1.cp.agent.borrower.profiles.delete')

                                        @if($record->is_enabled &&  $record->id != session('borrower_profile_id'))
                                            <a class="btn btn-sm grey-salsa btn-outline"
                                               href="{{url('borrower/profiles/'.$record->id.'/select')}}">
                                                <i class="fa fa-bookmark"></i>
                                                <span class="hidden-xs"> {{trans('messages.profiles.set_active')}} </span>
                                            </a>
                                        @endif

                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-js-pugins')
    <script src="{{asset('assets/global/scripts/datatable.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"
            type="text/javascript"></script>
    <script src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}"
            type="text/javascript"></script>

@endsection

@section('page-scripts')
    <script src="{{asset('assets/loan-app/scripts/datatable-no-options.js')}}"></script>
@endsection