routes/web.php
<?php

Route::group(['namespace' => 'Sentinel'], function () {
    Route::middleware('guest')->group(function () {
        Route::get('login', 'LoginController@getLogin');
        Route::get('signup', 'RegisterController@getRegister');

        Route::get('signup/borrower/{profile_type?}', 'RegisterController@getRegisterBorrower');
        Route::get('signup/lender', 'RegisterController@getRegisterLender');

        Route::post('signup/borrower', 'RegisterController@postRegisterBorrower');
        Route::post('signup/lender', 'RegisterController@postRegisterLender');

        Route::get('activate/{user}/{activation_code}', 'ActivationController@getActivate');

        Route::get('forgot/password', 'ForgotPasswordController@getForgetPassword');
        Route::post('forgot/password', 'ForgotPasswordController@postForgetPassword');
        Route::get('forgot/confrm', 'ForgotPasswordController@getForgetConfirm');

        Route::get('reset/password/{user}/{reset_code}', 'ResetPasswordController@getResetPassword');
        Route::post('reset/password', 'ResetPasswordController@postResetPassword');
        Route::get('reset/error', 'ResetPasswordController@getResetError');

        Route::get('get-loans', 'RegisterController@getRegisterBorrower');
        Route::get('aspire-borrowers', 'RegisterController@getRegisterBorrower');
    });

    Route::post('login', 'LoginController@postLogin');
    Route::get('logout', 'LoginController@getLogout');
});

Route::group(['namespace' => 'Admin'], function () {
    Route::get('institutions/check_domain_taken', 'InstitutionController@isNewDomainValid');
    Route::get('users/check_email_exists', 'UserController@isNewEmailValid');

    Route::get('states/check_enabled', 'StateController@checkEnabled');
    Route::get('states/check_city_enabled', 'StateController@checkCityEnabled');

    Route::get('states/check_zipcode_enabled', 'StateController@checkZipCodeEnabled');
    Route::get('states/check_valid_zip_code', 'StateController@checkValidZipCode');
});
Route::group(['prefix' => 'dropdowns'], function () {
    Route::get('zip_codes', 'DropdownsControllers@zipCodes'); //dy mfrod tb2a zip_codes
    Route::get('zip_codes_for_city', 'DropdownsControllers@zipCodesForCity');

    Route::get('cities', 'DropdownsControllers@cities'); //dy mfrood tb2a cities

    Route::get('states', 'DropdownsControllers@states');

    Route::get('counties', 'DropdownsControllers@counties');
});

Route::middleware(['auth', 'web', 'permissions'])->group(function () {

    Route::get('/', 'HomeController@getIndex')->name('home');

    Route::middleware('subscribed')->group(function () {
        Route::get('braintree/token', 'BraintreeTokenController@token');
        Route::resource('subscribe', 'SubscriptionsController');
    });

    Route::get('user/invoice/{invoice}', 'SubscriptionsController@invoice');

    Route::post('upload_files', 'AttachmentController@uploadFiles')->name('upload_files');
    Route::post('upload_file', 'AttachmentController@uploadFile')->name('upload_file');
    Route::resource('attachment', 'AttachmentController');

    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'admin'], function () {

        Route::get('/', 'DashboardController@getIndex')->name('admin.home');

        Route::get('dashboard', 'DashboardController@getIndex')->name('dashboard');
        Route::get('dashboard_2', 'DashboardController@getIndex2')->name('dashboard2');
        Route::get('dashboard_3', 'DashboardController@getIndex3')->name('dashboard3');

        Route::group(['prefix' => 'institutions'], function () {

            Route::put('{institution}/change_status', 'InstitutionController@changeStatus')->name('institutions.change_status');
            Route::get('institution_loan_handling_chart', 'InstitutionController@institutionLoanHandlingChart'); //Returns JSON
        });

        Route::resource('institutions', 'InstitutionController');

        Route::put('institution_types/{institution_type}/change_status', 'InstitutionTypeController@changeStatus')->name('institution_types.change_status');
        Route::resource('institution_types', 'InstitutionTypeController');

        Route::put('institution_sizes/{institution_size}/change_status', 'InstitutionSizeController@changeStatus')->name('institution_sizes.change_status');
        Route::resource('institution_sizes', 'InstitutionSizeController');

        Route::group(['prefix' => 'users'], function () {
            Route::put('{user}/change_status', 'UserController@changeStatus')->name('users.change_status');
            Route::get('{user}/tracks/{user_track}', 'UserController@showTrack')->name('users.track'); //to be checked
        });
        Route::resource('users', 'UserController');

        Route::get('lenders_per_state', 'UserController@lendersPerState');

        Route::get('number_of_lenders_per_institution', 'UserController@numberOfLendersPerInstitution');

        Route::get('loans_feedback_statistics', 'FeedbackController@loansFeedbackStatistics');

        Route::resource('roles', 'RoleController');

        Route::put('real_estate_types/{real_estate_type}/change_status', 'RealEstateTypeController@changeStatus')->name('real_estate_types.change_status');
        Route::resource('real_estate_types', 'RealEstateTypeController');

        Route::put('property_types/{property_type}/change_status', 'PropertyTypeController@changeStatus')->name('property_types.change_status');
        Route::resource('property_types', 'PropertyTypeController');

        Route::put('purpose_types/{purpose_type}/change_status', 'PurposeTypeController@changeStatus')->name('purpose_types.change_status');
        Route::resource('purpose_types', 'PurposeTypeController');

        Route::put('lease_types/{lease_type}/change_status', 'LeaseTypeController@changeStatus')->name('lease_types.change_status');
        Route::resource('lease_types', 'LeaseTypeController');

        Route::resource('settings', 'SettingController');

        Route::group(['prefix' => 'states/{state}'], function () {

            Route::put('change_status', 'StateController@changeStatus')->name('states.change_status'); //done
            Route::get('counties', 'StateController@counties')->name('counties.index');

            Route::group(['prefix' => 'counties'], function () {
                Route::post('select_all' , 'StateController@selectAllCounties');
                Route::post('unselect_all' , 'StateController@unselectAllCounties');

                Route::put('{county}/change_status', 'StateController@changeCountyStatus')->name('counties.change_status');
                Route::get('{county}/cities', 'StateController@cities')->name('cities.index');

                Route::post('{county}/cities/select_all' , 'StateController@selectAllCities') ;
                Route::post('{county}/cities/unselect_all' , 'StateController@unselectAllCities') ;

                Route::group(['prefix' => '{county}/cities/{city}'], function () {
                    Route::post('zip_codes/select_all' , 'StateController@selectAllZipCodes') ;
                    Route::post('zip_codes/unselect_all' , 'StateController@unselectAllZipCodes') ;

                    Route::put('change_status', 'StateController@changeCityStatus')->name('cities.change_status');
                    Route::get('zip_codes', 'StateController@zip_codes')->name('zip_codes.index');

                    Route::group(['prefix' => 'zip_codes/{zip_code}'], function () {
                        Route::put('change_status', 'StateController@changeZipCodeStatus')->name('zip_codes.change_status');
                    });
                });
            });

        });
        Route::post('states/select_all', 'StateController@selectAllStates');
        Route::post('states/unselect_all', 'StateController@unselectAllStates');

        Route::resource('states', 'StateController');

        Route::get('loans/bids/{bid}/show', 'LoanController@showBid');
        Route::get('loans/bids', 'LoanController@bids');

        Route::resource('loans', 'LoanController');

        Route::get('loans_count', 'LoanController@loansCount'); // Returns JSON
        Route::get('loans_status_statistics', 'LoanController@loansStatusStatistics'); //Returns JSON
        Route::get('total_number_of_loans', 'LoanController@totalNumberOfLoans'); // Returns JSON


    });

    Route::group(['namespace' => 'Agent'], function () {

        Route::get('profile', 'UserController@show')->name('profile');
        Route::get('account', 'UserController@edit')->name('account');

        Route::get('preferences', 'PreferenceController@index')->name('preferences.index');

        Route::group(['prefix' => 'users'], function () {
            Route::put('{user}/account_settings', 'UserController@update')->name('user.account_settings');
            Route::put('{user}/change_password', 'UserController@changePassword')->name('user.change_password');
            Route::put('{user}/change_picture', 'UserController@changePicture')->name('user.change_picture');
            Route::put('{user}/notification_settings', 'UserController@updatePreferences')->name('user.notification_settings');
            Route::put('{user}/preferences', 'UserController@updatePreferences')->name('user.preferences');
        });

        Route::put('notifications/{notification}/mark_read', 'NotificationController@markAsRead')->name('notification.mark_read');
        Route::put('notifications/mark_all_read', 'NotificationController@markAllRead')->name('notifications.mark_all_read');

        Route::resource('notifications', 'NotificationController');

        Route::post('conversations/{conversation}/replies', 'ConversationController@addReply')->name('conversation.add_reply');
        Route::put('conversations/mark_all_read', 'ConversationController@markAllRead')->name('conversations.mark_all_read');

app/Models/Loan.php
<?php

namespace App\Models;

use App\Enums\BorrowerProfileTypes;
use App\Enums\LoanStatuses;
use Illuminate\Database\Eloquent\Model;
use Sentinel;

class Loan extends Model
{
    protected $guarded = [];

    /*Relations*/
    public function details()
    {
        return $this->hasOne('App\Models\LoanDetail', 'loan_id');
    }

    public function preferences()
    {
        return $this->hasMany('App\Models\Preference', 'loan_id')->where('loan_id','<>',null);
    }

    public function tenants()
    {
        return $this->hasMany('App\Models\Tenant', 'loan_id');
    }

    public function borrower()
    {
        return $this->belongsTo('App\Models\User', 'borrower_id')->withTrashed();
    }

    public function borrower_profile()
    {
        return $this->belongsTo('App\Models\BorrowerProfile', 'profile_id');
    }

    public function bids()
    {
        return $this->hasMany('App\Models\Bid', 'loan_id');
    }

    public function archived()
    {
        return $this->belongsToMany('App\Models\User', 'loan_archive', 'loan_id', 'user_id');
    }

    public function attachments()
    {
        return $this->morphMany('App\Models\Attachment', 'attachable');
    }

    /*scopes*/
    public function scopeActiveBorrowerProfile($query)
    {
        return $query->where('borrower_id', Sentinel::getUser()->id)
            ->where('profile_id', session('borrower_profile_id'));
    }

    public function scopeActive($query)
    {
        return $query->where('status', '<>', LoanStatuses::DELETED)
            ->where('status', '<>', LoanStatuses::EXPIRED)
            ->where('status', '<>', LoanStatuses::CLOSED)
            ;
    }

    public function scopePublished($query)
    {
        return $query->where('status', '<>', LoanStatuses::DELETED)
            ->where('status', '<>', LoanStatuses::EXPIRED)
            ->where('status', '<>', LoanStatuses::DRAFT)
            ->where('status', '<>', LoanStatuses::CLOSED)
            ;
    }

    public function scopeExpired($query)
    {
        return $query->where('status', LoanStatuses::EXPIRED);
    }

    public function scopeDeleted($query)
    {
        return $query->where('status', LoanStatuses::DELETED);
    }

    public function scopeOfStatus($query, $type)
    {
        return $query->where('status', $type);
    }

//    public function scopeArchived($query)
//    {
//        return $query->where('lender_archived', 0);
//    }
//
//    public function scopeNotArchived($query)
//    {
//        return $query->where('lender_archived', 0);
//    }


    /*acccessors*/
    public function getIsActiveAttribute($query)
    {
        return $this->status != LoanStatuses::EXPIRED && $this->status != LoanStatuses::DELETED& $this->status != LoanStatuses::CLOSED;
    }

    public function getCompanyNameAttribute($query)
    {
        return $this->borrower_profile->profile_type == BorrowerProfileTypes::BUSINESS ?
            $this->borrower_profile->profile->business_name
            : $this->borrower->full_name;
    }

    public function getFullAddressAttribute()
    {
        return ($this->apt_suite_no && $this->apt_suite_no != 0 ? ($this->apt_suite_no . ", ") : '')
            . ($this->address ? ($this->address . ", ") : '')
            . ($this->city ? ($this->city . ", ") : '')
            . ($this->state ? $this->state->state . " " : '')
            . ($this->zip_code ? ($this->zip_code) : '');
    }
//    public function getRequestedValueAttribute($query)
//    {
//        return $this->details->requested_amount ? $this->details->requested_amount : $this->details->requested_percent;
//    }

}

app/Http/Controllers/Frontend/Lender/LoanController.php
<?php

namespace App\Http\Controllers\Frontend\Lender;

use App\Traits\ControllersTrait;
use App\Http\Controllers\Controller;

class LoanController extends Controller
{
    use ControllersTrait;

    public function findLoans()
    {
        return view('v1.cp.frontend.lender.loans.index');
    }
}

resources/views/v1/cp/components/loans/bid_details.blade.php
<div class="blog-single-content bordered blog-container">
    <div class="blog-single-head">
        <h1 class="blog-single-head-title">{{trans('messages.bids.bid_details')}}</h1>
    </div>
    <div class="blog-single-desc">

        <div class="row static-info">
            <div class="col-md-3 name"> {{trans('messages.bids.rate')}}</div>
            <div class="col-md-7 value"> {{$bid->rate}}</div>
        </div>

        <div class="row static-info">
            <div class="col-md-3 name"> {{trans('messages.bids.term')}}</div>
            <div class="col-md-1 value"> {{$bid->term}}</div>
            <div class="col-md-3 value"> {{$bid->term_unit}}</div>
        </div>

        <div class="row static-info">
            <div class="col-md-3 name"> {{trans('messages.bids.amortization')}}</div>
            <div class="col-md-1 value"> {{$bid->amortization}}</div>
            <div class="col-md-3 value"> {{$bid->amortization_unit}}</div>
        </div>

        <div class="row static-info">
            <div class="col-md-3 name"> {{trans('messages.bids.description')}}</div>
            <div class="col-md-7 value"> {{$bid->descripton}}</div>
        </div>


    </div>
</div>

resources/views/v1/cp/components/loans/bid_status.blade.php
<h4 class="block">
    <span class="label label-{{\App\Helpers\ViewHelper::getBidStatusLabel($bid->status)}}"> {{ BidStatuses::items()[$bid->status]}} </span>
</h4>

resources/views/v1/cp/components/loans/bids_admin.blade.php
<div class="blog-single-content bordered blog-container">
    <div class="blog-single-head">
        <h1 class="blog-single-head-title">{{trans('messages.bids.bids')}} ({{count($loan->bids)}})</h1>
    </div>
    <div class="blog-single-desc">
        @if(isset($loan->bids) && count($loan->bids) > 0)
            @foreach($loan->bids as $bid)
                <table class="table table-bordered table-advance table-hover">
                    <thead>
                    <tr>
                        <th>{{trans('messages.bids.lender')}}</th>
                        <th>{{trans('messages.bids.rate')}}</th>
                        <th>{{trans('messages.bids.term')}}</th>
                        <th>{{trans('messages.bids.amortization')}}</th>
                        <th>{{trans('messages.bids.status')}}</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="hidden-xs">{{$bid->lender->full_name}}</td>
                        <td class="hidden-xs">{{$bid->rate}}</td>
                        <td class="hidden-xs">{{$bid->term . ' '.$bid->term_unit}}</td>
                        <td class="hidden-xs">{{$bid->amortization. ' '.$bid->amortization_unit}}</td>
                        <td class="hidden-xs"><span
                                    class="label label-{{ViewHelper::getBidStatusLabel($bid->status)}}">{{\App\Enums\BidStatuses::items()[$bid->status]}}</span>
                        </td>
                        <td>
                            <a class="btn btn-sm grey-salsa btn-outline"
                               href="{{url('admin/loans/bids/'.$bid->id.'/show')}}">
                                <i class="fa fa-eye"></i>
                                <span class="hidden-xs"> View </span>
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>

            @endforeach
        @endif
    </div>
</div>

resources/views/v1/cp/components/loans/building_sq_ft.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.building_sq_ft')}}:
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="building_sq_ft" id="building_sq_ft"
               value="{{old('building_sq_ft') ? old('building_sq_ft') : (isset($loan) ? $loan->details->building_sq_ft : '')}}"
               placeholder="{{trans('messages.loans.building_sq_ft')}}">
        <span class="alert-danger"><?php echo $errors->first('building_sq_ft') ?></span>
    </div>
</div>

@if(isset($display_tips) && $display_tips)
    <span class="help-block">{{trans('messages.loans.building_sq_ft_tips')}}</span>

    <div class="form-group">
        <label class="col-md-4 control-label">{{trans('messages.loans.tips')}}:
        </label>
        <div class="col-md-5">
            <input type="text" class="form-control" name="tips" id="tips"
                   value="{{old('tips') ? old('tips') : (isset($loan) ? $loan->details->tips : '')}}"
                   placeholder="{{trans('messages.loans.tips')}}">
            <span class="alert-danger"><?php echo $errors->first('tips') ?></span>
        </div>
    </div>
@endif

resources/views/v1/cp/components/loans/company_revenue.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.gross_annual_revenue')}}:
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="gross_annual_revenue" id="gross_annual_revenue"
               value="{{old('gross_annual_revenue') ? old('gross_annual_revenue') : (isset($loan) ? $loan->details->gross_annual_revenue : '')}}"
               placeholder="{{trans('messages.loans.gross_annual_revenue')}}">
        <span class="alert-danger"><?php echo $errors->first('gross_annual_revenue') ?></span>
    </div>
</div>

resources/views/v1/cp/components/loans/conversation.blade.php
@if($bid->conversation->replies)
    <div class="blog-single-content bordered blog-container">
        <div class="blog-single-head">
            <h1 class="blog-single-head-title">{{trans('messages.bids.messages')}}</h1>
        </div>
        <div class="blog-single-desc">
            <div id="chats">
                <div class="scroller" style="height: 525px;" data-always-visible="1" data-rail-visible1="1">
                    <ul class="chats" data-id="{{$bid->id}}">
                        @foreach($bid->conversation->replies as $reply)
                            @include('v1.cp.components.conversations.reply',['reply'=>$reply,"bid"=>$bid])
                        @endforeach
                    </ul>
                    <div id="CanFollowUpMessage"></div>
                </div>
                @if($logged_in_user->status != ActivationStates::SUSPENDED && $bid->loan->is_active)
                    <div class="chat-form">
                        <div class="input-cont">
                            <input class="form-control" type="text" id="message" name="message"
                                   placeholder="{{trans('messages.conversations.type_message')}}"/></div>
                        <div class="btn-cont">
                            <span class="arrow"> </span>

                            <input type="hidden" class="btn-follow-up" id="btn-follow-up" data-id="{{$bid->loan->id}}"
                                   data-csrf="{{csrf_token()}}" data-content="{{$logged_in_user->inRole(\App\Services\RoleService::ROLE_LENDER) ? 1 : 0}}"
                                   data-action="{{url('bids/'.$bid->id.'/follow_up_number')}}" >

                            <a href="" class="btn blue icn-only reply"
                               data-csrf="{{csrf_token()}}"
                               data-user_id="{{$logged_in_user->id}}"
                               data-action="{{url('conversations/' . $bid->conversation->id.'/replies')}}"
                            >
                                <i class="fa fa-check icon-white"></i>
                            </a>
                        </div>

                        @if(!$borrower_replied && $bid->status == BidStatuses::NO_RESPONSE && $logged_in_user->inRole(\App\Services\RoleService::ROLE_BORROWER))
                            <br/>
                            <a class="btn red btn-block not_interested"
                               href="{{url('borrower/loans/bids/' . $bid->id.'/not_interested')}}">{{trans('messages.bids.not_interested')}}</a>
                        @endif
                    </div>
                @endif
            </div>
        </div>
    </div>
@endif

resources/views/v1/cp/components/loans/equipment_age.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.equipment_age')}}
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="equipment_age" id="equipment_age"
               value="{{old('equipment_age') ? old('equipment_age') : (isset($loan) ? $loan->details->equipment_age : '')}}"
               placeholder="{{trans('messages.loans.equipment_age')}}">
        <span class="alert-danger"><?php echo $errors->first('equipment_age') ?></span>
    </div>
</div>

resources/views/v1/cp/components/loans/funded_debt.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.funded_debt')}}
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="funded_debt" id="funded_debt"
               value="{{old('funded_debt') ? old('funded_debt') : (isset($loan) ? $loan->details->funded_debt : '')}}"
               placeholder="{{trans('messages.loans.funded_debt')}}">
        <span class="help-block">{{trans('messages.loans.funded_debt_hint')}}</span>
        <span class="alert-danger"><?php echo $errors->first('funded_debt') ?></span>
    </div>
</div>

resources/views/v1/cp/components/loans/gross_annual_revenue.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.gross_annual_revenue')}}:
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="gross_annual_revenue" id="gross_annual_revenue"
               value="{{old('gross_annual_revenue') ? old('gross_annual_revenue') : (isset($loan) ? $loan->details->gross_annual_revenue : '')}}"
               placeholder="{{trans('messages.loans.gross_annual_revenue')}}">
        <span class="alert-danger"><?php echo $errors->first('gross_annual_revenue') ?></span>
    </div>
</div>

resources/views/v1/cp/components/loans/loan_amount.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.requested_amount')}}:
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control mask_money" name="requested_amount" id="requested_amount"
               value="{{old('requested_amount') ? old('requested_amount') : (isset($loan) ? $loan->details->requested_amount : '')}}"
               placeholder="{{trans('messages.loans.requested_amount')}}">
        <span class="alert-danger"><?php echo $errors->first('requested_amount') ?></span>
    </div>
</div>

resources/views/v1/cp/components/loans/other_required_loans.blade.php
<div class="blog-single-content bordered blog-container">
    <div class="blog-single-head">
        <h1 class="blog-single-head-title">{{trans('messages.loans.other_required_loans')}} (#)</h1>
    </div>
    <div class="blog-single-desc">
    </div>
</div>

resources/views/v1/cp/components/loans/owner_occupied_p_v.blade.php
<h5 class="form-section">
    <span class="bold">{{trans('messages.loans.owner_occupied_percent')}}</span>
    <span class="help-block">* {{trans('messages.loans.owner_occupied_hint')}}</span>
</h5>

<div class="form-group">
    <label class="control-label col-md-4">{{trans('messages.loans.percent')}}</label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="owner_occupied_percent" id="owner_occupied_percent"
               value="{{old('owner_occupied_percent') ? old('owner_occupied_percent') : (isset($loan) ? $loan->details->owner_occupied_percent : '')}}"
               placeholder="{{trans('messages.loans.percent')}}">
        <span class="help-block"> {{$errors->first('owner_occupied_percent')}} </span>
    </div>
    <div class="col-md-3">
        <span class="help-block bold">{{trans('messages.common.or')}}</span>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-4">{{trans('messages.loans.number')}}</label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="owner_occupied_no" id="owner_occupied_no"
               value="{{old('owner_occupied_no') ? old('owner_occupied_no') : (isset($loan) ? $loan->details->owner_occupied_no : '')}}"
               placeholder="{{trans('messages.loans.number')}}">
        <span class="help-block"> {{$errors->first('owner_occupied_no')}} </span>
    </div>
    <div class="col-md-3">
        <span class="help-block bold">%</span>
    </div>
</div>

resources/views/v1/cp/components/loans/rental_annual_revenue.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.rental_annual_revenue')}}:
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="rental_annual_revenue" id="rental_annual_revenue"
               value="{{old('rental_annual_revenue') ? old('rental_annual_revenue') : (isset($loan) ? $loan->details->rental_annual_revenue : '')}}"
               placeholder="{{trans('messages.loans.rental_annual_revenue')}}">
        <span class="alert-danger"><?php echo $errors->first('rental_annual_revenue') ?></span>
    </div>
</div>

resources/views/v1/cp/components/loans/rental_revenue_by_tenants.blade.php
<div class="form-group">
    <label class="col-md-4 control-label">{{trans('messages.loans.rental_revenue_by_tenants_text')}}:
    </label>
    <div class="col-md-5">
        <input type="text" class="form-control" name="rental_revenue_by_tenants" id="rental_revenue_by_tenants"
               value="{{old('rental_revenue_by_tenants') ? old('rental_revenue_by_tenants') : (isset($loan) ? $loan->details->rental_revenue_by_tenants : '')}}"
               placeholder="{{trans('messages.loans.rental_revenue_by_tenants')}}">
        <span class="alert-danger"><?php echo $errors->first('rental_revenue_by_tenants') ?></span>
    </div>
</div>