routes/web.php
<?php

Route::group(['namespace' => 'Sentinel'], function () {
    Route::middleware('guest')->group(function () {
        Route::get('login', 'LoginController@getLogin');
        Route::get('signup', 'RegisterController@getRegister');

        Route::get('signup/borrower/{profile_type?}', 'RegisterController@getRegisterBorrower');
        Route::get('signup/lender', 'RegisterController@getRegisterLender');

        Route::post('signup/borrower', 'RegisterController@postRegisterBorrower');
        Route::post('signup/lender', 'RegisterController@postRegisterLender');

        Route::get('activate/{user}/{activation_code}', 'ActivationController@getActivate');

        Route::get('forgot/password', 'ForgotPasswordController@getForgetPassword');
        Route::post('forgot/password', 'ForgotPasswordController@postForgetPassword');
        Route::get('forgot/confrm', 'ForgotPasswordController@getForgetConfirm');

        Route::get('reset/password/{user}/{reset_code}', 'ResetPasswordController@getResetPassword');
        Route::post('reset/password', 'ResetPasswordController@postResetPassword');
        Route::get('reset/error', 'ResetPasswordController@getResetError');

        Route::get('get-loans', 'RegisterController@getRegisterBorrower');
        Route::get('aspire-borrowers', 'RegisterController@getRegisterBorrower');
    });

    Route::post('login', 'LoginController@postLogin');
    Route::get('logout', 'LoginController@getLogout');
});

Route::group(['namespace' => 'Admin'], function () {
    Route::get('institutions/check_domain_taken', 'InstitutionController@isNewDomainValid');
    Route::get('users/check_email_exists', 'UserController@isNewEmailValid');

    Route::get('states/check_enabled', 'StateController@checkEnabled');
    Route::get('states/check_city_enabled', 'StateController@checkCityEnabled');

    Route::get('states/check_zipcode_enabled', 'StateController@checkZipCodeEnabled');
    Route::get('states/check_valid_zip_code', 'StateController@checkValidZipCode');
});
Route::group(['prefix' => 'dropdowns'], function () {
    Route::get('zip_codes', 'DropdownsControllers@zipCodes'); //dy mfrod tb2a zip_codes
    Route::get('zip_codes_for_city', 'DropdownsControllers@zipCodesForCity');

    Route::get('cities', 'DropdownsControllers@cities'); //dy mfrood tb2a cities

    Route::get('states', 'DropdownsControllers@states');

    Route::get('counties', 'DropdownsControllers@counties');
});

Route::middleware(['auth', 'web', 'permissions'])->group(function () {

    Route::get('/', 'HomeController@getIndex')->name('home');

    Route::middleware('subscribed')->group(function () {
        Route::get('braintree/token', 'BraintreeTokenController@token');
        Route::resource('subscribe', 'SubscriptionsController');
    });

    Route::get('user/invoice/{invoice}', 'SubscriptionsController@invoice');

    Route::post('upload_files', 'AttachmentController@uploadFiles')->name('upload_files');
    Route::post('upload_file', 'AttachmentController@uploadFile')->name('upload_file');
    Route::resource('attachment', 'AttachmentController');

    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'admin'], function () {

        Route::get('/', 'DashboardController@getIndex')->name('admin.home');

        Route::get('dashboard', 'DashboardController@getIndex')->name('dashboard');
        Route::get('dashboard_2', 'DashboardController@getIndex2')->name('dashboard2');
        Route::get('dashboard_3', 'DashboardController@getIndex3')->name('dashboard3');

        Route::group(['prefix' => 'institutions'], function () {

            Route::put('{institution}/change_status', 'InstitutionController@changeStatus')->name('institutions.change_status');
            Route::get('institution_loan_handling_chart', 'InstitutionController@institutionLoanHandlingChart'); //Returns JSON
        });

        Route::resource('institutions', 'InstitutionController');

        Route::put('institution_types/{institution_type}/change_status', 'InstitutionTypeController@changeStatus')->name('institution_types.change_status');
        Route::resource('institution_types', 'InstitutionTypeController');

        Route::put('institution_sizes/{institution_size}/change_status', 'InstitutionSizeController@changeStatus')->name('institution_sizes.change_status');
        Route::resource('institution_sizes', 'InstitutionSizeController');

        Route::group(['prefix' => 'users'], function () {
            Route::put('{user}/change_status', 'UserController@changeStatus')->name('users.change_status');
            Route::get('{user}/tracks/{user_track}', 'UserController@showTrack')->name('users.track'); //to be checked
        });
        Route::resource('users', 'UserController');

        Route::get('lenders_per_state', 'UserController@lendersPerState');

        Route::get('number_of_lenders_per_institution', 'UserController@numberOfLendersPerInstitution');

        Route::get('loans_feedback_statistics', 'FeedbackController@loansFeedbackStatistics');

        Route::resource('roles', 'RoleController');

        Route::put('real_estate_types/{real_estate_type}/change_status', 'RealEstateTypeController@changeStatus')->name('real_estate_types.change_status');
        Route::resource('real_estate_types', 'RealEstateTypeController');

        Route::put('property_types/{property_type}/change_status', 'PropertyTypeController@changeStatus')->name('property_types.change_status');
        Route::resource('property_types', 'PropertyTypeController');

        Route::put('purpose_types/{purpose_type}/change_status', 'PurposeTypeController@changeStatus')->name('purpose_types.change_status');
        Route::resource('purpose_types', 'PurposeTypeController');

        Route::put('lease_types/{lease_type}/change_status', 'LeaseTypeController@changeStatus')->name('lease_types.change_status');
        Route::resource('lease_types', 'LeaseTypeController');

        Route::resource('settings', 'SettingController');

        Route::group(['prefix' => 'states/{state}'], function () {

            Route::put('change_status', 'StateController@changeStatus')->name('states.change_status'); //done
            Route::get('counties', 'StateController@counties')->name('counties.index');

            Route::group(['prefix' => 'counties'], function () {
                Route::post('select_all' , 'StateController@selectAllCounties');
                Route::post('unselect_all' , 'StateController@unselectAllCounties');

                Route::put('{county}/change_status', 'StateController@changeCountyStatus')->name('counties.change_status');
                Route::get('{county}/cities', 'StateController@cities')->name('cities.index');

                Route::post('{county}/cities/select_all' , 'StateController@selectAllCities') ;
                Route::post('{county}/cities/unselect_all' , 'StateController@unselectAllCities') ;

                Route::group(['prefix' => '{county}/cities/{city}'], function () {
                    Route::post('zip_codes/select_all' , 'StateController@selectAllZipCodes') ;
                    Route::post('zip_codes/unselect_all' , 'StateController@unselectAllZipCodes') ;

                    Route::put('change_status', 'StateController@changeCityStatus')->name('cities.change_status');
                    Route::get('zip_codes', 'StateController@zip_codes')->name('zip_codes.index');

                    Route::group(['prefix' => 'zip_codes/{zip_code}'], function () {
                        Route::put('change_status', 'StateController@changeZipCodeStatus')->name('zip_codes.change_status');
                    });
                });
            });

        });
        Route::post('states/select_all', 'StateController@selectAllStates');
        Route::post('states/unselect_all', 'StateController@unselectAllStates');

        Route::resource('states', 'StateController');

        Route::get('loans/bids/{bid}/show', 'LoanController@showBid');
        Route::get('loans/bids', 'LoanController@bids');

        Route::resource('loans', 'LoanController');

        Route::get('loans_count', 'LoanController@loansCount'); // Returns JSON
        Route::get('loans_status_statistics', 'LoanController@loansStatusStatistics'); //Returns JSON
        Route::get('total_number_of_loans', 'LoanController@totalNumberOfLoans'); // Returns JSON


    });

    Route::group(['namespace' => 'Agent'], function () {

        Route::get('profile', 'UserController@show')->name('profile');
        Route::get('account', 'UserController@edit')->name('account');

        Route::get('preferences', 'PreferenceController@index')->name('preferences.index');

        Route::group(['prefix' => 'users'], function () {
            Route::put('{user}/account_settings', 'UserController@update')->name('user.account_settings');
            Route::put('{user}/change_password', 'UserController@changePassword')->name('user.change_password');
            Route::put('{user}/change_picture', 'UserController@changePicture')->name('user.change_picture');
            Route::put('{user}/notification_settings', 'UserController@updatePreferences')->name('user.notification_settings');
            Route::put('{user}/preferences', 'UserController@updatePreferences')->name('user.preferences');
        });

        Route::put('notifications/{notification}/mark_read', 'NotificationController@markAsRead')->name('notification.mark_read');
        Route::put('notifications/mark_all_read', 'NotificationController@markAllRead')->name('notifications.mark_all_read');

        Route::resource('notifications', 'NotificationController');

        Route::post('conversations/{conversation}/replies', 'ConversationController@addReply')->name('conversation.add_reply');
        Route::put('conversations/mark_all_read', 'ConversationController@markAllRead')->name('conversations.mark_all_read');

app/Models/LoanDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class LoanDetail extends Model
{
    protected $guarded = [];

    public function loan()
    {
        return $this->belongsTo('App\Models\Loan', 'loan_id');
    }

    public function purpose_type()
    {
        return $this->belongsTo('App\Models\PurposeType', 'purpose_type_id');
    }


    public function the_city()
    {
        return $this->belongsTo('App\Models\City', 'zip_code', 'zip_code');
    }

    public function state()
    {
        return $this->belongsTo('App\Models\State', 'state_code', 'state_code');
    }

    public function getCountyAttribute()
    {
        return $this->the_city->county;
    }


    public function real_estate_type()
    {
        return $this->belongsTo('App\Models\RealEstateType', 'real_estate_type_id');
    }

    /*Accessors*/
    public function getRequestedValueAttribute()
    {
        $value = null != $this->requested_amount ? $this->requested_amount : $this->requested_percent;
        return ($value);
    }

    public function getOutstandingValueAttribute($value)
    {
        return number_format((int)($value));
    }


    public function getRequestedAmountAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getLessTradeAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getLessDownPaymentAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getEstimatedPropertyValueAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getEstimatedMarketPriceAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getReceivableRangeFromAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getReceivableRangeToAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getInventoryRangeFromAttribute($value)
    {
        return isset($value) ? number_format((int)($value)) : "";
    }

    public function getInventoryRangeToAttribute($value)
    {
        return isset($value) ? number_format((int)($value)) : "";
    }

    public function getPurchasePriceAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getCashBeforeDownPaymentAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getGrossAnnualRevenueAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getEstimatedAnnualExpensesAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getEstimatedNetOperatingIncomeAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getNetOperatingIncomeAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getAnnualIncomeFromTenantsAttribute($value)
    {
        return number_format((int)($value));
    }


    public function getCompanyEBITDAAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getTotalLiabilitiesAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getFundedDebtAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getTangibleNetWorthAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getRentalAnnualRevenueAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getCashLiquidInvestmentsAttribute($value)
    {
        return number_format((int)($value));
    }

    public function getRentalRevenueByTenantsAttribute($value)
    {
        return number_format((int)($value));
    }


    public function getFullAddressAttribute()
    {
        return ($this->apt_suite_no && $this->apt_suite_no != 0 ? ($this->apt_suite_no . ", ") : '')
            . ($this->address ? ($this->address . ", ") : '')
            . ($this->city ? ($this->city . ", ") : '')
            . ($this->state ? $this->state->state . " " : '')
//            . " -- ".($this->the_city ? $this->the_city->county . "  -- " : '')
            . ($this->zip_code ? ($this->zip_code) : '');
    }

}

resources/views/v1/cp/components/loans/elements/view/building_sq_ft.blade.php
@if(isset($loan->details->building_sq_ft) && $loan->details->building_sq_ft != null)
    <div class="row static-info">
        <div class="col-md-3 name"> {{trans('messages.loans.building_sq_ft')}}</div>
        <div class="col-md-7 value"> {{$loan->details->building_sq_ft}}
        </div>
    </div>
@endif

@if(isset($loan->details->buildings_no) && $loan->details->buildings_no != null)
    <div class="row static-info">
        <div class="col-md-3 name"> {{trans('messages.loans.buildings_no')}}</div>
        <div class="col-md-7 value"> {{$loan->details->buildings_no}}
        </div>
    </div>
    <div class="row static-info">
        <div class="col-md-3 name"> {{trans('messages.loans.units_no')}}</div>
        <div class="col-md-7 value"> {{$loan->details->units_no}}
        </div>
    </div>
@endif
@if($loan->details->tips)
    <div class="col-md-3 name"> {{trans('messages.loans.building_sq_ft_tips')}}</div>
    <div class="col-md-7 value"> {{$loan->details->tips}}
    </div>
@endif

resources/views/v1/cp/components/loans/elements/view/cash_before_down_payment.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.cash_before_down_payment')}}</div>
    <div class="col-md-7 value"> {{$loan->details->cash_before_down_payment}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/equipment_finance_type.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.equipment_finance_type')}}</div>
    <div class="col-md-7 value"> {{\App\Enums\EquipmentFinanceTypes::all()[$loan->details->equipment_finance_type] }}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/equipment_type.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.equipment_type')}}</div>
    <div class="col-md-7 value"> {{$loan->details->equipment_type}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/estimated_market_price.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.estimated_market_price')}}</div>
    <div class="col-md-7 value"> $ {{$loan->details->estimated_market_price}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/estimated_property_value.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.estimated_property_value')}}</div>
    <div class="col-md-7 value"> $ {{$loan->details->estimated_property_value}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/funded_debt.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.funded_debt')}}</div>
    <div class="col-md-7 value"> {{$loan->details->funded_debt}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/loan_moving_from_leased.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.is_moving_from_leased')}}</div>
    <div class="col-md-2 value"> {{ $loan->details->is_moving_from_leased == 1 ?trans('messages.common.yes') : trans('messages.common.no')}}
    </div>
    @if($loan->details->current_lease_expense)
        <div class="col-md-2 name"> {{trans('messages.loans.current_lease_expense')}}</div>
        <div class="col-md-2 value"> {{$loan->details->current_lease_expense}}
        </div>
    @endif
</div>

resources/views/v1/cp/components/loans/elements/view/loan_outstanding.blade.php
<div class="row static-info">
    <div class="col-md-2 name"> {{trans('messages.loans.'.$title_key)}}</div>
    <div class="col-md-3 value"> {{$loan->details->is_loan_outstanding == 1 ?trans('messages.common.yes') : trans('messages.common.no')}}
    </div>

    <div class="col-md-2 name"> {{trans('messages.loans.outstanding_value')}}</div>
    <div class="col-md-3 value"> $ s{{$loan->details->outstanding_value}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/loan_requested.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.loan_requested')}}</div>
    <div class="col-md-2 name"> {{trans('messages.loans.amount')}}</div>
    <div class="col-md-2 value"> {{$loan->details->requested_amount}}
    </div>
    <div class="col-md-2 name"> {{trans('messages.loans.percent')}}</div>
    <div class="col-md-2 value"> {{$loan->details->requested_percent}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/net_operating_income.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.net_operating_income')}}</div>
    <div class="col-md-7 value"> $ {{$loan->details->net_operating_income}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/purpose-text.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.purpose_type')}}</div>
    <div class="col-md-7 value"> {{$loan->details->purpose}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/receivable_range.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.receivable_range_title')}}</div>
    <div class="col-md-3 value"> $ {{$loan->details->receivable_range_from}}
    </div>
    <div class="col-md-3 value"> $ {{$loan->details->receivable_range_to}}
    </div>
</div>

resources/views/v1/cp/components/loans/elements/view/total_liabilities.blade.php
<div class="row static-info">
    <div class="col-md-3 name"> {{trans('messages.loans.total_liabilities')}}</div>
    <div class="col-md-7 value"> {{$loan->details->total_liabilities}}
    </div>
</div>